[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Recipes"
  weight = 20
  identifier = "recipes"
  url = "/docs/recipes/"

[[docs]]
  name = "Reference Guides"
  weight = 30
  identifier = "reference-guides"
  url = "/docs/reference-guides/"

[[docs]]
  name = "Extensions"
  weight = 40
  identifier = "extensions"
  url = "/docs/extensions/"

[[docs]]
  name = "Contributing"
  weight = 50
  identifier = "contributing"
  url = "/docs/contributing/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[main]]
  name = "Who We Are"
  url = "/about/"
  weight = 10

[[main]]
  name = "Solutions"
  url = "/solutions/"
  weight = 20

[[main]]
  name = "News & Insights"
  url = "/blog/"
  weight = 30

[[main]]
  name = "Careers"
  url = "/careers/"
  weight = 40

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/hafzanholdings"
  weight = 10
  
#[[main]]
 # name = "Community"
 # url = "https://github.com/h-enk/hyas/discussions"
 # weight = 50

# [[footer]]
#   name = "Community"
#   url = "https://github.com/h-enk/hyas/discussions"
#   weight = 30

[[showcase]]
  name = "Browse"
  weight = 10
  identifier = "browse"
  url = "/showcase/"

[[secondary]]
  name = "Submit to Themes"
  url = "https://github.com/h-enk/hyas/discussions?discussions_q=category%3A%22Show+and+tell%22"
  weight = 10

[[themes]]
  name = "Browse"
  weight = 10
  identifier = "browse"
  url = "/themes/"

[[tertiary]]
  name = "Submit to Showcase"
  url = "https://github.com/h-enk/hyas/discussions?discussions_q=category%3A%22Show+and+tell%22"
  weight = 10
